FROM dunglas/frankenphp

# Environment variables
ENV APP_ENV=prod
ENV PUID=1001
ENV PGID=1001
ENV USER=koillection
ENV FRANKENPHP_CONFIG="worker /app/public/public/index.php"
ENV FRANKENPHP_SERVER_NAME=":80"
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY ./ /app/public
COPY ./docker/Caddyfile /etc/caddy/Caddyfile

# Install some basics dependencies
RUN apt-get update && \
    apt-get install -y curl wget lsb-release gnupg2 && \
# Add User and Group
    addgroup --gid "$PGID" "$USER" && \
    adduser --gecos '' --no-create-home --disabled-password --uid "$PUID" --gid "$PGID" "$USER" && \
# Nodejs
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=21 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
# Install packages
    apt-get update && \
    apt-get install -y \
    libnss3 \
    nss-plugin-pem \
    ca-certificates \
    apt-transport-https \
    nodejs \
    git \
    unzip \
    openssl && \
# Install PHP extensions
    install-php-extensions opcache pdo_pgsql pdo_mysql intl gd zip apcu curl && \
#Install composer dependencies
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    cd /app/public && \
    composer install --classmap-authoritative && \
    composer clearcache && \
# Dump translation files for javascript
    cd /app/public && \
    php bin/console app:translations:dump && \
# Install javascript dependencies and build assets
    corepack enable && \
    cd /app/public/assets && \
    yarn --version && \
    yarn install && \
    yarn build && \
# Clean up
    yarn cache clean --all && \
    rm -rf /app/public/assets/.yarn/cache && \
    rm -rf /app/public/assets/.yarn/install-state.gz && \
    rm -rf /app/public/assets/node_modules && \
    apt-get purge -y wget lsb-release git nodejs apt-transport-https ca-certificates gnupg2 unzip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/local/bin/composer && \
# Set permissions
    chown -R "$USER":"$USER" /app/public && \
    chmod +x /app/public/docker/entrypoint-frankenphp.sh && \
    mkdir /run/php && \
# Add PHP config files
    cp /app/public/docker/php-frankenphp.ini /usr/local/etc/php/conf.d/php.ini

# Install curl-impersonate
ADD https://github.com/lwthiker/curl-impersonate/releases/download/v0.6.1/libcurl-impersonate-v0.6.1.x86_64-linux-gnu.tar.gz /opt/
RUN cd /opt && tar xvzf libcurl-impersonate-v0.6.1.x86_64-linux-gnu.tar.gz && rm libcurl-impersonate-v0.6.1.x86_64-linux-gnu.tar.gz

VOLUME /uploads

EXPOSE 80
EXPOSE 443

WORKDIR /app/public

HEALTHCHECK CMD curl --fail http://localhost:80/ || exit 1

ENTRYPOINT ["sh", "/app/public/docker/entrypoint-frankenphp.sh" ]